export const data = [
  { name: "Hand Tossed", size: "large", price: "$20.99" },
  { name: "Hand Tossed", size: "small", price: "$7.99" },
  { name: "Crunchy Thin", size: "large", price: "$9.99" },
  { name: "Cheeses Pizza", size: "x-large", price: "$7.99" },
  { name: "Cheeses Pizza", size: "x-large", price: "$7.99" },
  { name: "Crust Cheeses", size: "x-small", price: "$5.99" },
  { name: "Crust Cheeses", size: "x-small", price: "$5.99" },
  { name: "Hand Tossed", size: "small", price: "$7.99" },
  { name: "Crunchy Thin", size: "large", price: "$11.99" },
  { name: "Hand Tossed", size: "small", price: "$7.99" },
  { name: "Crunchy Thin", size: "large", price: "$12.99" },
  { name: "Crunchy Thin", size: "large", price: "$12.99" },
  { name: "Crunchy Thin", size: "large", price: "$12.99" },
];
